In [7]:
from ReplayBuffer import ReplayBuffer
from DQN_Solver import DQN_Solver
from env import MPSPEnv
from DQN import DQN
import numpy as np
import wandb
import torch
import os
os.environ['WANDB_NOTEBOOK_NAME'] = 'main.ipynb'
wandb.login()

wandb: WARNING Calling wandb.login() after wandb.init() has no effect.


True

In [8]:
config = {
    # Env
    'ROWS': 3,
    'COLUMNS': 3,
    'N_PORTS': 4,
    # Training
    'EPISODES': 1000,
    'LEARNING_RATE': 0.0001,
    'MEM_SIZE': 10000,
    'BATCH_SIZE': 64,
    'GAMMA': 0.95,
    'EXPLORATION_MAX': 1.0,
    'EXPLORATION_DECAY': 0.999,
    'EXPLORATION_MIN': 0.001,
    # Model
    'HIDDEN_SIZE_1': 1024,
    'HIDDEN_SIZE_2': 512,
}

In [9]:
env = MPSPEnv(
    config['ROWS'],
    config['COLUMNS'],
    config['N_PORTS']
)
# We flatten the observation space
config['OBSERVATION_SPACE'] = (
    np.prod(env.observation_space[0].shape) +
    np.prod(env.observation_space[1].shape)
)
config['ACTION_SPACE'] = env.action_space.n

In [10]:
wandb.init(
    project="Q-learning",
    entity="rl-msps",
    name=f"{config['ROWS']}x{config['COLUMNS']}_{config['N_PORTS']}-ports",
    config=config,
    tags=["test"]
)

wandb: ERROR Control-C detected -- Run data was not synced


Thread SenderThread:
Traceback (most recent call last):
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 50, in run
    self._run()
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    self._process(record)
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 308, in _process
    self._sm.send(record)
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 305, in send
    send_handler(record)
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 319, in send_request
    send_handler(record)
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 486, in send_request_defer
    transition_state()
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/

Problem at: /var/folders/j8/qdr4bmbd6vv8nydcr40cfdhw0000gn/T/ipykernel_60707/2595097054.py 1 <module>


Traceback (most recent call last):
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/Users/axelhojmark/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
wandb: ERROR Abnormal program exit


Exception: problem

In [ ]:
ReplayBuffer = ReplayBuffer(
    mem_size=config['MEM_SIZE'],
    observation_space=config['OBSERVATION_SPACE'],
    batch_size=config['BATCH_SIZE']
)
DQN = DQN(
    input_size=config['OBSERVATION_SPACE'],
    output_size=config['ACTION_SPACE'],
    hidden_size_1=config['HIDDEN_SIZE_1'],
    hidden_size_2=config['HIDDEN_SIZE_2'],
    learning_rate=config['LEARNING_RATE']
)
agent = DQN_Solver(
    ReplayBuffer=ReplayBuffer,
    DQN=DQN,
    batch_size=config['BATCH_SIZE'],
    exploration_max=config['EXPLORATION_MAX'],
    gamma=config['GAMMA'],
    exploration_decay=config['EXPLORATION_DECAY'],
    exploration_min=config['EXPLORATION_MIN']
)


In [ ]:
for i in range(1, config['EPISODES']):
    state, info = env.reset()
    state = np.concatenate((state[0].flatten(), state[1].flatten()))
    score = 0
    sum_loss = 0
    count = 0

    while True:
        action = agent.choose_action(state, info['mask'], env)
        state_, reward, done, info = env.step(action)
        state_ = np.concatenate((state_[0].flatten(), state_[1].flatten()))
        agent.memory.add(state, action, reward, state_, done)
        sum_loss += agent.learn()
        state = state_
        score += reward
        count += 1

        if done:
            wandb.log({
                "Episode Reward": score,
                "Average Episode Loss": sum_loss / count,
                "Exploration Rate": agent.exploration_rate
            })
            break


Port: 1
Bay matrix:
[[3 2 2]
 [3 3 2]
 [3 3 3]]
Transportation matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [0 0 0 0]]
Port: 1
Bay matrix:
[[3 2 2]
 [3 3 2]
 [3 3 3]]
Transportation matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [0 0 0 0]]
Blocking containers: 0
Port: 2
Bay matrix:
[[3 2 2]
 [3 3 2]
 [3 3 3]]
Transportation matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [0 0 0 0]]
Port: 2
Bay matrix:
[[3 0 0]
 [3 3 0]
 [3 3 3]]
Transportation matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [0 0 0 0]]
Blocking containers: 0


wandb: Network error (ReadTimeout), entering retry loop.


Port: 3
Bay matrix:
[[0 3 3]
 [3 3 3]
 [3 3 3]]
Transportation matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Port: 3
Bay matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Transportation matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Blocking containers: 0


KeyboardInterrupt: Interrupted by user

In [ ]:
torch.save(DQN.state_dict(), os.path.join(wandb.run.dir, "dqn.pt"))
wandb.finish()